# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0002_auto_20161219_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='culture.user'),
        ),
        migrations.AlterField(
            model_name='per',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='culture.user'),
        ),
    ]
